name: Comment on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt-get update
          sudo apt-get install gh

      - name: Comment on Pull Request
        run: |
          COMMENT="Thank you for the new commit! 🚀"
          ISSUE_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          echo "COMMENT: $COMMENT"
          echo "ISSUE_NUMBER: $ISSUE_NUMBER"

          gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
          gh issue comment $ISSUE_NUMBER --body "$COMMENT"
