name: Comment on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on Pull Request
        run: |
          COMMENT="Thank you for the new commit! 🚀"
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER=$(echo ${{ github.event_path }} | jq --raw-output .pull_request.number)

          echo "COMMENT: $COMMENT"
          echo "ISSUE_NUMBER: $ISSUE_NUMBER"

          gh issue comment $ISSUE_NUMBER --body "$COMMENT"
